version: "3"
services:

  # application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
    depends_on:
      - database

  # web server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www:ro
    ports:
      - 8080:80
    depends_on:
      - app

  # database
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "33061:3306"

volumes:
  dbdata: